config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  root to: 'static_pages#home'
  post '/', to: 'static_pages#create', as: 'search'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'crawl', to: 'sales#new'
  
  resources :users, :sales

end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  before_save {
    self.email = self.email.downcase
  }
  validates :name, presence: true, length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  validates :url, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 50}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  require 'open-uri'
  #require 'JSON'
  require 'nokogiri'
  
  # ヤフーショッピングのアプリケーションID
  y_app_id = 'dj0zaiZpPXFkdlVWczZkV0RMayZzPWNvbnN1bWVyc2VjcmV0Jng9ODQ-'

  def new
    @sale = Sale.new
  end
  
  def create
    res = JSON.parse open('https://shopping.yahooapis.jp/ShoppingWebService/V1/json/itemSearch?appid=y_app_id&query=%E6%A5%BD%E5%99%A8').read
    #@res_url = []
    # res.each{|key, value|
    #   if(key == 'ResultSet')
    #     res['ResultSet'].each{|key, value|
    #       if(key == "0")
    #         res['ResultSet']["0"].each{|key, value|
    #           if(key == "0")
    #             @res_url =  res['ResultSet']["0"]
    #             # res['ResultSet']['0']['0'].each{|key, value|
    #             # @res_url[key] = value
    #             #   # if(key == "Url")
    #             #   #   @res_url = value
    #             #   # end
    #             # }
    #           end
    #         }
    #       end
    #     }
    #   end
    # }
    
    # # カテゴリ情報を取得
    # cate_id_api = "http://shopping.yahooapis.jp/ShoppingWebService/V1/categorySearch?appid=y_app_id&category_id=1"
    
    # cate_xml = Nokogiri::XML(open(cate_id_api), nil, "utf-8")

    # @cate_ids = []
    # cate_xml.xpath('/children/child').each do |child|
    #   @cate_ids.push(child["id"])
    # end
    
    
    #url = "http://shopping.yahooapis.jp/ShoppingWebService/V1/itemSearch?appid=y_app_id"
    #@doc = Nokogiri::HTML(open(url), nil, "utf-8")
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to crawl_path
    else
      flash[:danger] = 'invalid name/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user

  def home
    @shops = Shop.all
  end
  
  def create
    require 'nokogiri'
    # 検索したキーワードは保存される→カラムを追加
    # 危険な仕様の修正が残った場合は内容のみ教えて頂く
    # 最後の２回はメール配信を少しでも教えて頂く
    # 検索したキーワード毎にDMの反応を保存できる
    require 'open-uri'
    require 'cgi'
    
    keyword = CGI.escape(params[:q])
    
    app_id = ENV['YAHOO_APPLICATION_ID']
    offset = 0
    i = 0
    res_nums = 0
    total_count = 0

    loop do
      offset = 50 * i
      responces = JSON.parse open("https://shopping.yahooapis.jp/ShoppingWebService/V1/json/itemSearch?appid=#{app_id}&offset=#{offset}&hits=50&query=#{keyword}").read
      keys = responces['ResultSet']["0"]["Result"].keys
      keys.shift
      keys.shift
      keys.pop
      keys.each do |key|
        shop = {}
        shop.store(:url, 'http://store.shopping.yahoo.co.jp/' + responces['ResultSet']["0"]["Result"][key]['Url'].split('/')[3] + "/info.html")
        shop.store(:name, responces['ResultSet']["0"]["Result"][key]['Store']['Name'])
        Nokogiri::HTML(open(shop[:url])).xpath('//*[@id="CentInfoPage1"]/div[3]/div/table').text.match(/([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+/)
        shop.store(:email, $&)
        @shop = Shop.new(shop)
        if @shop.save
          res_nums += 1
        end
        if total_count == 20 || res_nums == 10
          @shops = Shop.all
          return render 'static_pages/home'
        end
        total_count += 1
        sleep([*3..6].sample)
      end
      i += 1
    end
    
    # @address = []
    
    # @urls.each.with_index(1) do |url, i|
    #   result = Nokogiri::HTML(open(url)).xpath('//*[@id="CentInfoPage1"]/div[3]/div/table').text.match(/([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+/)
    #   @address << result
    #   sleep([*3..6].sample)
    #   puts "***#{i}回目***"
    #   puts result
    #   if i == 10
    #     return render 'static_pages/home'
    #   end
    # end
    @shops = Shop.all
    render 'static_pages/home'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the MyCrawler!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MyCrawler", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCrawler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/sales/create.html.erb
<%= @res_url %>

app/views/sales/new.html.erb
<h1>Sales</h1>

<div class="row">
  <div class="col-md-3">
    <%= form_for(@sale) do |f| %>
      <%= f.submit "To Crawl Yahoo! Shopping", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>MyCrawler Top</h1>
<p>This is the top page of mycrawler.</p>

<%#= link_to "探す", search_path, method: :post %><br><br>

<%= form_tag search_path do %>
  <%= text_field_tag :q, params[:q], required: true %>
  <%= submit_tag "検索",name: nil, data: { disable_with: "検索中..."} %> 
<% end %>



<div id="loader-bg">
  <div id="loader">
    <img src="img-loading.gif" width="80" height="80" alt="Now Loading..." />
    <p>Now Loading...</p>
  </div>
</div>
<div id="wrap">
  <ul>
    <% @shops.each do |shop| %>
      <li><%= shop.name %></li>
      <li><%= shop.url %></li>
      <li><%= shop.email %></li>
    <% end %>
  </ul>
</div>

<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
<script>
$(function() {
  var h = $(window).height();
 
  $('#wrap').css('display','none');
  $('#loader-bg ,#loader').height(h).css('display','block');
});
 
$(window).load(function () { //全ての読み込みが完了したら実行
  $('#loader-bg').delay(900).fadeOut(800);
  $('#loader').delay(600).fadeOut(300);
  $('#wrap').css('display', 'block');
});
 
// //10秒たったら強制的にロード画面を非表示
// $(function(){
//   setTimeout('stopload()',10000);
// });
 
// function stopload(){
//   $('#wrap').css('display','block');
//   $('#loader-bg').delay(900).fadeOut(800);
//   $('#loader').delay(600).fadeOut(300);
// }
</script>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>